java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252)
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:701)
	at cs451.udp.UDPReceiver.run(UDPReceiver.java:47)
Caused by: java.nio.channels.AsynchronousCloseException
	at java.base/sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:523)
	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:677)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:635)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
	... 2 more
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@39b7306[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@440a690a[Wrapped task = Thread[Thread-2117702,9,main]]] rejected from java.util.concurrent.ThreadPoolExecutor@779a197b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2117696]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at cs451.links.FairLossLinks.send(FairLossLinks.java:65)
	at cs451.links.StubbornLinks.lambda$sendMessagesToBeSent$3(StubbornLinks.java:142)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at cs451.links.StubbornLinks.sendMessagesToBeSent(StubbornLinks.java:133)
	at cs451.links.StubbornLinks.lambda$new$2(StubbornLinks.java:111)
	at java.base/java.lang.Thread.run(Thread.java:833)
