Exception in thread "Thread-2" java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "cs451.interfaces.LatticeDeliverer.getProposal(int)" is null
	at cs451.links.PerfectLinks.deliver(PerfectLinks.java:129)
	at cs451.links.StubbornLinks.deliver(StubbornLinks.java:174)
	at cs451.links.FairLossLinks.deliver(FairLossLinks.java:103)
	at cs451.udp.UDPReceiver.lambda$new$0(UDPReceiver.java:41)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252)
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:701)
	at cs451.udp.UDPReceiver.run(UDPReceiver.java:57)
Caused by: java.nio.channels.AsynchronousCloseException
	at java.base/sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:523)
	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:677)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:635)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
	... 2 more
